### ISSUE TITLE
Site Launch Checklist

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin.org#218]
- [ ] Migrate plugin API docs and add sidebar link
- [ ] Announcement blog post
- [ ] Remove site banner
- [ ] Update README
- [ ] Update GH repository description
- [ ] Update DNS
